version: "3.7"

services:
  web:
    build: .
    command: >
      bash -c "bundle check || bundle install &&
      rm -f /app/tmp/pids/server.pid &&
      bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle-volume:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "pay_bills_on_time_api_development"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  bundle-volume:
  postgres-data: