default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pay_bills_on_time_api_development

test:
  <<: *default
  database: pay_bills_on_time_api_test

production:
  <<: *default
  database: pay_bills_on_time_api_production
  username: pay_bills_on_time_api
  password: <%= ENV["PAY_BILLS_ON_TIME_DATABASE_PASSWORD"] %>

