name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out the code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.3
      - name: Setup Rubocop
        run: |
          gem install --no-document rubocop -v '>= 1.0, < 2.0'
      - name: Rubocop Report
        run: rubocop --color
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out the code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.x
      - name: Setup RSpec
        run: |
          [ -f Gemfile ] && bundle install
          gem install --no-document rspec -v '>= 3.0, < 4.0'
      - name: RSpec Report
        run: rspec --force-color --format documentation
